server:
  port: 8888

spring:
  application:
    name: GETWAY-CENTER
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

zuul:
  retryable: true #是否重试，默认 false
  #表示禁用默认路由，只认我们自己配置的路由
  ignored-services: '*'
  add-host-header: true #请求路由转发前为请求设置Host头信息
  #过滤客户端请求中和该配置匹配的header
  sensitive-headers: '*'
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    UAA-CENTER:
      stripPrefix: false #默认为true 所有/demo/xxxx的请求转发给http://demo.com.cn/xxxx ,去除掉demo前缀
      path: /uaa/** #注意，两个*，一个会报404
    FASHION-CENTER:
      stripPrefix: false
      path: /fashion/**

feign:
  hystrix:
    enabled: true #开启hystrix支持
  compression:
    request:
      enabled: true #配置请求GZIP压缩开启
      mime-types:   #配置压缩支持的MIME 类型
        - text/html
        - application/xml
        - application/json
      min-request-size: 2048 #配置压缩数据的大小
    response:
      enabled: true #配置响应GZIP压缩开启

logging:
  level:
    root: info
    ort.springframework: info