server:
  port: 9999
  servlet:
    context-path: /uaa
  tomcat:
    remote-ip-header: x-forwarded-for #意思看下面解释
    protocol-header: x-forwarded-proto
  use-forward-headers: true
spring:
  application:
    name: UAA
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fashion?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  type-aliases-package: com.fashion.uaa.dao
  mapper-locations:
    - classpath:mapper/*Mapper.xml
logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env


#  x-forwarded-for 当你使用了代理时，web服务器就不知道你的真实IP了，为了避免这个情况，代理服务器通常会增加一个叫做x_forwarded_for的头信息，把连接它的客户端IP（即你的上网机器IP）加到这个头信息里，这样就能保证网站的web服务器能获取到真实IP